# Generated by Django 2.1.2 on 2019-01-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_document_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
